import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedBayarWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedBCAVirtualAccountWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle93Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle96Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/Generated8905000Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedGroup139Widget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle100Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle85Widget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedPerumTirtasaniBlokE211KarangplosoMalangWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/Generated2636127388Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRumahWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedLogoBCA_BiruWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedJNERegWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle85Widget2.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/Generated1Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedPilihmetodePembayaranWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle89Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle95Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedPs5DigitalEditionWidget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle91Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle94Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedGroup53Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRp3050000Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle98Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRifat085763671478Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle92Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedBarangyangdibeliWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedPengirimandanpembayaranWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedPilihKurirWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedGroup138Widget4.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle99Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratediconarrowbackoutlineWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall6widget/generated/GeneratedRectangle97Widget.dart';

/* Frame Android Small - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 140.0,
                child: GeneratedRectangle89Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 20.0,
                child: GeneratedRectangle91Widget(),
              ),
              Positioned(
                left: 90.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 51.0,
                child: GeneratedRectangle92Widget(),
              ),
              Positioned(
                left: 293.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 10.0,
                child: GeneratedRectangle93Widget(),
              ),
              Positioned(
                left: -4.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 260.0,
                child: GeneratedRectangle94Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 20.0,
                child: GeneratedRectangle95Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 52.0,
                child: GeneratedRectangle96Widget(),
              ),
              Positioned(
                left: 315.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 45.0,
                child: Generated1Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 52.0,
                child: GeneratedRectangle97Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 52.0,
                child: GeneratedRectangle98Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedRectangle85Widget1(),
              ),
              Positioned(
                left: 198.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 30.0,
                child: GeneratedGroup48Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 23.0,
                child: GeneratedRp3050000Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 40.0,
                child: GeneratedGroup53Widget(),
              ),
              Positioned(
                left: 243.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 38.0,
                child: GeneratedBayarWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 42.0,
                child: GeneratedBarangyangdibeliWidget(),
              ),
              Positioned(
                left: 100.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 28.0,
                child: GeneratedPs5DigitalEditionWidget1(),
              ),
              Positioned(
                left: 330.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 8.0,
                child: GeneratedRectangle99Widget(),
              ),
              Positioned(
                left: 294.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 8.0,
                child: GeneratedRectangle100Widget(),
              ),
              Positioned(
                left: 332.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 30.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 297.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 30.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 42.0,
                child: GeneratedPengirimandanpembayaranWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 36.0,
                child: GeneratedGroup138Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 36.0,
                child: GeneratedGroup139Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.0,
                child: GeneratedRectangle85Widget2(),
              ),
              Positioned(
                left: 100.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 32.0,
                child: Generated8905000Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 19.0,
                child: GeneratedRumahWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 16.0,
                child: GeneratedPerumTirtasaniBlokE211KarangplosoMalangWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 16.0,
                child: GeneratedRifat085763671478Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 13.0,
                child: GeneratedLogoBCA_BiruWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 10.0,
                child: Generated2636127388Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 16.0,
                child: GeneratedPilihmetodePembayaranWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 16.0,
                child: GeneratedBCAVirtualAccountWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 16.0,
                child: GeneratedJNERegWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 16.0,
                child: GeneratedPilihKurirWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10833333333333334;

                  final double height = constraints.maxHeight * 0.0609375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.002777777777777778,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
