import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedGroup162Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedLine137Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/Generatediconedit2outlineWidget6.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedLine138Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedUbahFotoProfilWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedLine139Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/Generatediconedit2outlineWidget7.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedNamaUsernameBioWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedLine141Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/Generatediconedit2outlineWidget3.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedInfoProfilWidget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedImage17Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedLine142Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedLine143Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedUserIDEmailNomorHPJenisKelaminTanggalLahirWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedLine136Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/Generatediconedit2outlineWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedSimpanProfilWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedLine140Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/Generatediconedit2outlineWidget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/Generatediconedit2outlineWidget5.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/Generatediconedit2outlineWidget2.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/Generatediconedit2outlineWidget4.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall8widget/generated/GeneratedInfoProfilWidget.dart';

/* Frame Android Small - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 138.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 83.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 117.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 42.0,
                child: GeneratedUbahFotoProfilWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 42.0,
                child: GeneratedInfoProfilWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 42.0,
                child: GeneratedInfoProfilWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 125.0,
                child: GeneratedNamaUsernameBioWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 202.0,
                child:
                    GeneratedUserIDEmailNomorHPJenisKelaminTanggalLahirWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 42.0,
                child: GeneratedSimpanProfilWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 40.0,
                child: GeneratedGroup162Widget(),
              ),
              Positioned(
                left: 136.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 85.0,
                child: GeneratedImage17Widget(),
              ),
              Positioned(
                left: 208.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 1.0,
                child: GeneratedLine136Widget(),
              ),
              Positioned(
                left: 208.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 1.0,
                child: GeneratedLine137Widget(),
              ),
              Positioned(
                left: 208.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 1.0,
                child: GeneratedLine138Widget(),
              ),
              Positioned(
                left: 208.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 1.0,
                child: GeneratedLine139Widget(),
              ),
              Positioned(
                left: 208.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 1.0,
                child: GeneratedLine140Widget(),
              ),
              Positioned(
                left: 208.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 1.0,
                child: GeneratedLine141Widget(),
              ),
              Positioned(
                left: 208.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 1.0,
                child: GeneratedLine142Widget(),
              ),
              Positioned(
                left: 208.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 1.0,
                child: GeneratedLine143Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.048804389105902776;

                  final double height =
                      constraints.maxHeight * 0.027452468872070312;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9083333333333333,
                        y: constraints.maxHeight * 0.340625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generatediconedit2outlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.048804389105902776;

                  final double height =
                      constraints.maxHeight * 0.027452468872070312;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9083333333333333,
                        y: constraints.maxHeight * 0.4046875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generatediconedit2outlineWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.048804389105902776;

                  final double height =
                      constraints.maxHeight * 0.027452468872070312;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9083333333333333,
                        y: constraints.maxHeight * 0.465625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generatediconedit2outlineWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.048804389105902776;

                  final double height =
                      constraints.maxHeight * 0.027452468872070312;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9083333333333333,
                        y: constraints.maxHeight * 0.6390625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generatediconedit2outlineWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.048804389105902776;

                  final double height =
                      constraints.maxHeight * 0.027452468872070312;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9083333333333333,
                        y: constraints.maxHeight * 0.7015625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generatediconedit2outlineWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.048804389105902776;

                  final double height =
                      constraints.maxHeight * 0.027452468872070312;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9083333333333333,
                        y: constraints.maxHeight * 0.7640625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generatediconedit2outlineWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.048804389105902776;

                  final double height =
                      constraints.maxHeight * 0.027452468872070312;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9083333333333333,
                        y: constraints.maxHeight * 0.8265625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generatediconedit2outlineWidget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.048804389105902776;

                  final double height =
                      constraints.maxHeight * 0.027452468872070312;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9083333333333333,
                        y: constraints.maxHeight * 0.8890625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generatediconedit2outlineWidget7(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
