import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup139Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup142Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup151Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup148Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedWishlistWidget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup140Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup141Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup147Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup143Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup153Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup149Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup145Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup146Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup144Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall14widget/generated/GeneratedGroup138Widget1.dart';

/* Frame Android Small - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall14Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 24.0,
                child: GeneratedWishlistWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup153Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup138Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup142Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup144Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup147Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup148Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup149Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup145Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup146Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup143Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup139Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup140Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup141Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedGroup151Widget(),
              )
            ]),
      ),
    ));
  }
}
