import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedGroup42Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedLoginWidget2.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedLoginWidget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedLoginWidget3.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedExpetasiaremovebgpreview4Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedGroup41Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall3widget/generated/GeneratedPasswordWidget.dart';

/* Frame Android Small - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 61.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 187.0,
                child: GeneratedGroup41Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 187.0,
                child: GeneratedGroup42Widget(),
              ),
              Positioned(
                left: 147.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 23.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 147.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 23.0,
                child: GeneratedLoginWidget1(),
              ),
              Positioned(
                left: 147.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 23.0,
                child: GeneratedLoginWidget2(),
              ),
              Positioned(
                left: 147.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 23.0,
                child: GeneratedLoginWidget3(),
              ),
              Positioned(
                left: 61.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 19.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 19.0,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 19.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup47Widget(),
              ),
              Positioned(
                left: 17.0,
                top: -28.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 126.0,
                child: GeneratedExpetasiaremovebgpreview4Widget(),
              )
            ]),
      ),
    ));
  }
}
