import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedGroup43Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedLine80Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedGroup43Widget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedKondisiBaruBeratSatuan10kgKategoriPlayStationEtalasePS5.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedRectangle84Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedExpetasiaremovebgpreview3Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedRectangle80Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedPs5DigitalEditionWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedBeliSekarangWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedRectangle83Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedGroup44Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedRp3000000Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedKeranjangWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedGroup45Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall25widget/generated/GeneratedLine79Widget.dart';

/* Frame Android Small - 25
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall25Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup43Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 42.0,
                child: GeneratedPs5DigitalEditionWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 285.0,
                height: 150.0,
                child: GeneratedRectangle83Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedRectangle84Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 30.0,
                child: GeneratedGroup45Widget(),
              ),
              Positioned(
                left: 198.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 30.0,
                child: GeneratedGroup44Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 37.0,
                child: GeneratedRectangle80Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 144.30870056152344,
                height: 1.0,
                child: GeneratedLine79Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 144.5544891357422,
                height: 1.0,
                child: GeneratedLine80Widget(),
              ),
              Positioned(
                left: 215.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 20.0,
                child: GeneratedBeliSekarangWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 23.0,
                child: GeneratedKeranjangWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 23.0,
                child: GeneratedRp3000000Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup43Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: -28.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 126.0,
                child: GeneratedExpetasiaremovebgpreview3Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 146.0,
                child:
                    GeneratedKondisiBaruBeratSatuan10kgKategoriPlayStationEtalasePS5(),
              ),
              Positioned(
                left: 20.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 271.0,
                child: GeneratedRectangle50Widget(),
              )
            ]),
      ),
    ));
  }
}
