import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall16widget/generated/GeneratedGroup163Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall16widget/generated/GeneratedPromoWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall16widget/generated/GeneratedBeliPS5DigitalEditionbisaraihCashbackextradarisellerpil.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall16widget/generated/GeneratedAkunmuTelahLoginmelaluiperangkatChrome106padaRabu12Octo.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall16widget/generated/GeneratedKamubarusajamembeliProdukPS4Pro500GBSeharga5999000Terim.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall16widget/generated/GeneratedRectangle106Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall16widget/generated/GeneratedRectangle105Widget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall16widget/generated/GeneratedInfoWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall16widget/generated/GeneratedRectangle107Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall16widget/generated/GeneratedTransaksiWidget.dart';

/* Frame Android Small - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedRectangle105Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedRectangle106Widget(),
              ),
              Positioned(
                left: -2.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedRectangle107Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 44.0,
                child:
                    GeneratedAkunmuTelahLoginmelaluiperangkatChrome106padaRabu12Octo(),
              ),
              Positioned(
                left: 6.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 45.0,
                child: GeneratedInfoWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 30.0,
                child:
                    GeneratedKamubarusajamembeliProdukPS4Pro500GBSeharga5999000Terim(),
              ),
              Positioned(
                left: 6.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 30.0,
                child:
                    GeneratedBeliPS5DigitalEditionbisaraihCashbackextradarisellerpil(),
              ),
              Positioned(
                left: 6.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 45.0,
                child: GeneratedTransaksiWidget(),
              ),
              Positioned(
                left: 4.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 45.0,
                child: GeneratedPromoWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 40.0,
                child: GeneratedGroup163Widget(),
              )
            ]),
      ),
    ));
  }
}
