import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall15widget/generated/GeneratedGroup154Widget2.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall15widget/generated/GeneratedGroup155Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall15widget/generated/GeneratedGroup152Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall15widget/generated/GeneratedGroup159Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall15widget/generated/GeneratedGroup161Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall15widget/generated/GeneratedTrollyWidget2.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall15widget/generated/GeneratedGroup154Widget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall15widget/generated/GeneratedGroup156Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall15widget/generated/GeneratedGroup160Widget.dart';

/* Frame Android Small - 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 24.0,
                child: GeneratedTrollyWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedGroup152Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup154Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup154Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup155Widget(),
              ),
              Positioned(
                left: 108.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup156Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup159Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup160Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup161Widget(),
              )
            ]),
      ),
    ));
  }
}
