import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup154Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup115Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup119Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedBestsaleWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup49Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup118Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedPaketHematWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedPromoHariiniWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratediconshoppingcartoutlineWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup114Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratediconbelloutlineWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedDiskonWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedLihatSemuaWidget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup117Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup120Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedImage16Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup121Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall24widget/generated/GeneratedGroup116Widget.dart';

/* Frame Android Small - 24
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall24Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 50.0,
                child: GeneratedGroup24Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup49Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 28.0,
                child: GeneratedPromoHariiniWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 31.0,
                child: GeneratedDiskonWidget(),
              ),
              Positioned(
                left: 148.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 28.0,
                child: GeneratedLihatSemuaWidget(),
              ),
              Positioned(
                left: 222.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 42.0,
                child: GeneratedPaketHematWidget(),
              ),
              Positioned(
                left: 299.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 42.0,
                child: GeneratedBestsaleWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup114Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup115Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup116Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup117Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup118Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup119Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup120Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup121Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 134.0,
                child: GeneratedImage16Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05274310641818576;

                  final double height =
                      constraints.maxHeight * 0.029667997360229494;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7972222222222223,
                        y: constraints.maxHeight * 0.0359375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconshoppingcartoutlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05274999936421712;

                  final double height =
                      constraints.maxHeight * 0.029671874642372132;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.9027777777777778,
                        y: constraints.maxHeight * 0.0359375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconbelloutlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedGroup154Widget(),
              )
            ]),
      ),
    ));
  }
}
