import 'package:flutter/material.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedGroup165Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedImage18Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedGroup164Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedGroup168Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedGroup162Widget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedRectangle115Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedGroup166Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedGroup169Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedGroup167Widget.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedGroup164Widget1.dart';
import 'package:flutterapp/mobileapp/generatedandroidsmall17widget/generated/GeneratedGroup163Widget1.dart';

/* Frame Android Small - 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall17Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 110.0,
                child: GeneratedRectangle115Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup162Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup166Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup163Widget1(),
              ),
              Positioned(
                left: 105.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup167Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup164Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup168Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup169Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 65.2996826171875,
                height: 92.0,
                child: GeneratedGroup165Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 40.0,
                child: GeneratedGroup164Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 110.0,
                child: GeneratedImage18Widget(),
              )
            ]),
      ),
    ));
  }
}
